### ISSUE TITLE
feature: add support for installing only specified browser dependencies

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-github-action#17]
It would be useful if we could do something like:

```yaml
      - uses: microsoft/playwright-github-action@v1
        with:
          browsers: chromium, webkit
```

or

```yaml
      - uses: microsoft/playwright-github-action@v1
        with:
          browsers: chromium
```

Since the apt calls are [already separate](https://github.com/microsoft/playwright-github-action/blob/master/index.js#L8) only a call to [getInput](https://github.com/actions/toolkit/tree/master/packages/core#inputsoutputs) and some parsing would be required.

(I'm open to collaborate for that feature)
