### ISSUE TITLE
Error with missing libraries

### ISSUE THREAD

**Issue by aomarks** [microsoft/playwright-github-action#31]
We often, but inconsistently, see errors from Playwright about missing libraries after `playwright-github-actions` has run, such as `libmozsqlite3.so` and `libxul.so`. So far I have only seen it affect Firefox. Example:

```
 ❌ Error: browserType.launch: Host system is missing dependencies!  (failed on Firefox)
      
      Missing libraries are:
      libmozsqlite3.so
      
      Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
      at validateDependenciesLinux (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/validateDependencies.js:131:11)
      at async validateDependencies (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/validateDependencies.js:45:16)
      at async Object.validateHostRequirements (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/validateDependencies.js:34:5)
      at async Firefox._launchServer (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/browserType.js:154:13)
      at async Firefox._innerLaunch (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/browserType.js:76:61)
      at async ProgressController.run (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/progress.js:75:28)
      at async Firefox.launch (/home/runner/work/lit-html/lit-html/packages/lit-html/node_modules/playwright/lib/server/browserType.js:62:25)
```

We are using this GitHub Actions config:

```
name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
```
