### ISSUE TITLE
Error with lerna bootstrap

### ISSUE THREAD

**Issue by aomarks** [microsoft/playwright-github-action#32]
There seems to be some odd interaction between the `lerna bootstrap` command and `playwright-github-action`. A majority of the time, if we run `lerna bootstrap` after `playwright-github-action`, we encounter the following error:

```
> node install.js


lerna ERR! npm ci stderr:

(node:7990) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '/home/runner/.cache/ms-playwright/chromium-792639/chrome-linux/chrome'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playwright@1.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

We are using this GitHub Actions config:

```
name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
```

Running `playwright-github-action` _after_ `lerna bootstrap` seems to work fine. No idea whether the source of this error is this action, Lerna, or somewhere else.
