### ISSUE TITLE
Webkit Not Found on Ubuntu (20.04 & 18.04)

### ISSUE THREAD

**Issue by davidteather** [microsoft/playwright-github-action#33]
I've been struggling to get webkit working on any ubuntu version using github actions. It works on mac and windows. I'm using playwright-python and running `python -m playwright install` to install however it's unable to detect the webkit binary on ubuntu. 

Is there something further I need to install so that playwright can find the webkit driver?

[Here's](https://github.com/davidteather/TikTok-Api/runs/1376500568) my GitHub action logs

Log in question
```
TikTokApi/browser.py:81: in __init__
    self.browser = playwright.webkit.launch(args=self.args, **self.options)
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/playwright/sync_api.py:6158: in launch
    firefoxUserPrefs=mapping.to_impl(firefoxUserPrefs),
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/playwright/sync_base.py:107: in _sync
    return future.result()
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/playwright/browser_type.py:72: in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
E   Exception: 
E   ================================================================================
E   "webkit" browser was not found.
E   Please complete Playwright installation via running
E   
E       "python -m playwright install"
E   
E   ================================================================================
=========================== short test summary info ============================
ERROR tests/test_byHashtag.py - Exception: 
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.19s ===============================
Error: Process completed with exit code 2.
```

Github actions
```
name: TikTokApi CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - nightly
      - 'releases/*'

jobs:
  Unit-Tests:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m playwright install

      - name: Run Tests
        run: pytest tests
```
