### ISSUE TITLE
Headful / headed runs failing on GitHub Actions (python-playwright / Chromium / Linux)

### ISSUE THREAD

**Issue by n8henrie** [microsoft/playwright-github-action#48]
I can't get headful runs to work using `python-playwright`; I keep getting `Unable to open X display.`.

I've tried for months with the recommended setup at https://playwright.dev/python/docs/ci#running-headed, and just today tried adding `--server-args="-screen 0 1280x960x24"` to the `xvfb-run` command to match your (passing) example [here](https://github.com/microsoft/playwright/blob/master/.github/workflows/tests_secondary.yml), but it's still not working.

I got some errors about the Chromium sandbox, so I added 

```
chromium_sandbox=False,
args=["--no-sandbox", "--disable-setuid-sandbox"],
```

but that didn't seem to help.

Currently on python 3.9.5, python-playwright 1.11.0, Ubuntu-20.04.

You can see my config at: https://github.com/n8henrie/pycookiecheat/blob/dev/.github/workflows/python-package.yml

At the time of opening this issue, it is:

```yaml
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: microsoft/playwright-github-action@v1
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- python -m tox -e py
    - name: Lint
      run: python -m tox -e lint
```

You can see my dozens of failing attempts to get this to run at: https://github.com/n8henrie/pycookiecheat/actions -- I'd love to hear any suggestions!

**Comment by mxschmitt** [comment]
You need to use xvfb-run, it might be different with tox: https://playwright.dev/docs/ci#running-headed

**Comment by n8henrie** [comment]
@mxschmitt   You may have noticed in my config above that I've been trying with xvfb-run.

**Comment by n8henrie** [comment]
Or perhaps that the headed documentation link you included in your response was already included in my question.

**Comment by mxschmitt** [comment]
Yes, it's likely that tox does some magic there and spawns maybe some sub-processes etc. I would recommend to not use tox and use a GitHub Actions matrix instead with your Python versions: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-running-multiple-versions-of-nodejs to workaround that.

**Comment by n8henrie** [comment]
@mxschmitt  No luck.

https://github.com/n8henrie/pycookiecheat/actions/runs/1150698104

```yaml
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: microsoft/playwright-github-action@v1
    - name: Run tests
      run: xvfb-run --auto-servernum -- python -m pytest
```
