### ISSUE TITLE
Conflicting package lists using playwright-github-action@v1

### ISSUE THREAD

**Issue by humphd** [microsoft/playwright-github-action#63]
I have a workflow that looks like this:

```yaml
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - uses: docker/setup-buildx-action@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Start microservices and run e2e tests
        run: |
          pnpm install
          pnpm services:start
          pnpm jest:e2e
```

It's suddenly started failing like this:

```
Run microsoft/playwright-github-action@v1
/usr/bin/sudo apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
Hit:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Get:[7](https://github.com/Seneca-CDOT/telescope/runs/5560042499?check_suite_focus=true#step:6:7) http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1642 kB]
Get:[8](https://github.com/Seneca-CDOT/telescope/runs/5560042499?check_suite_focus=true#step:6:8) http://azure.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [312 kB]
Get:[9](https://github.com/Seneca-CDOT/telescope/runs/5560042499?check_suite_focus=true#step:6:9) http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [14.8 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [853 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [122 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [910 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [202 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [20.3 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [23.8 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [580 B]
Get:17 http://azure.archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [42.2 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu focal-backports/main Translation-en [10.1 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [22.7 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [15.4 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [804 B]
Get:22 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1317 kB]
Get:23 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [231 kB]
Get:24 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [9808 B]
Get:25 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [799 kB]
Get:26 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [114 kB]
Get:27 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [692 kB]
Get:28 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [121 kB]
Get:29 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.0 kB]
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease (expected focal but got testing)
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Origin' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Label' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Codename' value from 'focal' to 'testing'
Error: The process '/usr/bin/sudo' failed with exit code [10](https://github.com/Seneca-CDOT/telescope/runs/5560042499?check_suite_focus=true#step:6:10)0
```

I wonder if there's something different I need to do, version-wise, or if this is a blip that will self-correct, or a bug that needs attention.

Thanks for any tips.
