### ISSUE TITLE
Remove `sudo` requirement in order to make the action work with act

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/playwright-github-action#7]
Hi, I'm trying to run my Playwright GitHub Actions locally in order to generate image snapshots without the issues produced by cross-platform inconsistencies.

To run my actions locally I'm using [act](https://github.com/nektos/act), but I'm having a problem because of the lack of `sudo` support in the `ubuntu-latest` act image. (the only working one is the complete `nektos/act-environments-ubuntu:18.04` image, but it's 18gb)

This is my action config:

```yml
jobs:
  functional-chromium:
    name: Chromium Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        env:
          RUNNER_TEMP: '/tmp/' # this is needed just to make `act` work
      - uses: microsoft/playwright-github-action@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run test:functional
        env:
          BROWSER: chromium
          CI: true
```

Would it be possible to remove `sudo` from the required executables? Or do you have other alternatives to run this action locally?

**Comment by arjun27** [comment]
Thanks for reporting this @FezVrasta. I've been trying out `act`, and the default image is very different from the `ubuntu-latest` on GHA (act uses `node:12.6-buster-slim`). Aside from the sudo requirement, it requires a completely different set of dependencies. I'll raise a PR when I have it working.

**Comment by FezVrasta** [comment]
Thanks for the reply. I think it's important to being able to run tests locally mostly because I'm having issues with them on GitHub Actions...

My tests are working correctly when ran with Puppeteer both on my macOS and on Travis CI. But now that I'm trying to migrate to GitHub Actions + Playwright I have issues with them.

I suspect it's not a matter of cross-platform inconsistencies because otherwise I would see the same problems with Puppeteer, but I can't think of any other way to debug the issue right now.

These are some failing image snapshots:

![image](https://user-images.githubusercontent.com/5382443/79039805-172ff400-7be4-11ea-86f6-0fdcbd44a49b.png)
![image](https://user-images.githubusercontent.com/5382443/79039826-3b8bd080-7be4-11ea-9c75-66a238ef5d07.png)

I feel like there's some more serious issue here, probably JavaScript is not running, or something. But locally everything looks good 🤷‍♂️

**Comment by DanJohnstonArmory** [comment]
Was this ever worked on? I'm running into the same issue
`[E2E Tests/e2e]   ☁  git clone 'https://github.com/microsoft/playwright-github-action' # ref=v1
[E2E Tests/e2e]   🐳  docker cp src=/Users/danjohnston/.cache/act/microsoft-playwright-github-action@v1 dst=/actions/
[E2E Tests/e2e]   ❗  ::error::Unable to locate executable file: sudo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

**Comment by leonardodino** [comment]
[this](https://github.com/leonardodino/setup-playwright) might help 😄
(on GitHub it's just a wrapper around this action. I was using the "slim" default debian images on [`act`](https://github.com/nektos/act))

**Comment by Th3S4mur41** [comment]
I'm getting a similar issue too trying to run a simple job on an ubuntu image (to avoid running directly in the self hosted runner OS).

```
Job: 
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci --no-optional --no-audit --prefer-offline --progress=false
      - run: npm run ci:playwright
```

```
/usr/bin/docker exec  3bf06d0553237cea82a3bdb498c8bd9376d57166fcd8035fc38260a29c8ac260 sh -c "cat /etc/*release | grep ^ID"
Error: Unable to locate executable file: sudo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
